version: '3'
services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
